### PR TITLE
authors and affiliation lookup examples added

### PR DESCRIPTION
**Pull request by Kris-LIBIS**
As requested I have added files to illustrate how we implemented the authors lookup at KU Leuven. Currently a config file and JavaScript file are added along with some documentation in the examples directory.

### CODE REVIEW

**Comment by pdurbin** [comment]
@Kris-LIBIS thanks! I haven't had a chance to dig into this but on a related note, do you think it's possible to search ROR to populate author affiliations? This was asked about here: https://groups.google.com/g/dataverse-community/c/498ElEzOBcg/m/Mn9-JC29DgAJ

**Comment by Kris-LIBIS** [comment]
@pdurbin It sure would. Put a search button after the affiliation input instead of the name field. Perform a query on ror.org instead of the 'covoc' server/solr index. Then some changes (mostly simplifications) to the copy-and-paste function is all that is needed. It could be another and probably simpler example of this feature.

**Comment by Kris-LIBIS** [comment]
@pdurbin I added the affiliation example to this PR as well. Should be pretty straightforward to implement and try out.

**Comment by pdurbin** [comment]
@Kris-LIBIS thanks! I'm hosting the .js file locally with Python's built in web server so I changed the following line...

`"js-url": "http://localhost:8000/scripts/affiliation.js",`

... before loading it into `:CVocConf`. However, Author Affiliation (citation block) hasn't turned into a field I can search. If it matters, I'm running Dataverse on port 8080 (in dev).

Maybe we can talk in https://chat.dataverse.org sometime to figure this out. Thanks for the example!

**Comment by Kris-LIBIS** [comment]
@pdurbin It worked for me, but there may be something I missed in the configuration. If you do not see the search icon next to the affiliation input field, you may want to check out your browser developer mode (F12) and see which error messages are printed on the console when you reload the page and enter the metadata editor.

**Comment by pdurbin** [comment]
@Kris-LIBIS thanks for all the help today! The version as of 376651d doesn't work for me but if I put the document.ready back in like before it seems to work. Please see [affiliation.js.txt](https://github.com/gdcc/dataverse-external-vocab-support/files/8044604/affiliation.js.txt) or the diff below:

```
$ git diff scripts/affiliation.js
diff --git a/scripts/affiliation.js b/scripts/affiliation.js
index dc438ac..4d1e394 100644
--- a/scripts/affiliation.js
+++ b/scripts/affiliation.js
@@ -26,13 +26,14 @@ var elementIdAttribute = 'data-affiliation-element-id';
  * added or removed. This code is reposible for creating the HTML for the dialog box, adding a search button to 
  * the affiliation name fields and creating the triggers for initializing the dialog box and the search action itself.
  */
-(function() {
+$(document).ready(function() {
+
   // Create Dialog box, if necessary
   createAffiliationModal();
 
   // Put a search button after each affiliation name field
   putAffiliationSearchIcon();
-})();
+});
 
 function createAffiliationModal() {
   let affiliationModal = document.getElementById(affiliationModalId);
```

**Comment by Kris-LIBIS** [comment]
I have undone that change. It did not help me with the CORS errors anyway. I realize now that jquery is not my issue.

**Comment by Kris-LIBIS** [comment]
Note: if you want to apply the affiliation lookup also to the Contacts affiliation, in the javascript file just change the definition of authorSelector into:
`var authorSelector = "#metadata_author ~ .dataset-field-values .edit-compound-field, #metadata_datasetContact ~ .dataset-field-values .edit-compound-field";` (single line of code)

**Comment by Kris-LIBIS** [comment]
Recent changes fixes a problem I noticed in our own installation. The JavaScript code would prevent the Dataset Template drop-down not to open. This is fixed in the patch.

**Pull request merged**
